name: test
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main    
  workflow_dispatch: 
jobs:
  validate-config:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name : Trigering update
      uses: ./.github/workflows/update-grm.yml 
