name: test
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main    
  workflow_dispatch: 
env:
    GH_TOKEN: ${{ github.GH_TOKEN }}
jobs:
  workflow-call:
    runs-on: ubuntu-latest
    steps:
    #- name: Checkout
      #uses: actions/checkout@v4
    - name : Trigering update
      run : gh workflow run update-grm.yml
         
