name: test
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main    
  workflow_dispatch: 
jobs:
  workflow-call:
    runs-on: ubuntu-latest
    steps:
    #- name: Checkout
      #uses: actions/checkout@v4
    - name : Trigering update
      run : |
          repo_owner=github.repository_owner 
          repo_name=github.event.repository.name 
          echo $repo_owner
          event_type="trigger-workflow" 
          

      
      #uses: ./.github/workflows/update-grm.yml 
