name: test
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main    
  workflow_dispatch: 

jobs: 
   workflow-call:
    runs-on: ubuntu-latest
    env: 
     GH_TOKEN: ${{secrets.GH_NEW}}
    steps:
    #- name: Checkout
      #uses: actions/checkout@v4
    - name : Trigering update
      run : gh workflow run update-grm.yml
         
